//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CzlonekZespolu
    {
        public int IdCzlonka { get; set; }
        public int IdPracownika { get; set; }
        public int IdZespolu { get; set; }
        public System.DateTime DataDolaczenia { get; set; }
        public Nullable<System.DateTime> DataOpuszczenia { get; set; }
        public string RolaWZespole { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual ZespolRatunkowy ZespolRatunkowy { get; set; }
    }
}
