//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktura()
        {
            this.KosztUtrzymania = new HashSet<KosztUtrzymania>();
            this.HistoriaNapraw = new HashSet<HistoriaNapraw>();
            this.PozycjaFaktury = new HashSet<PozycjaFaktury>();
        }
    
        public int IdFaktury { get; set; }
        public string Numer { get; set; }
        public System.DateTime DataWystawienia { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public string Waluta { get; set; }
        public string StatusPlatnosci { get; set; }
        public string Opis { get; set; }
        public string KategoriaKosztu { get; set; }
        public string OkresKsiegowy { get; set; }
        public bool CzyZatwierdzona { get; set; }
        public int IdKontrahenta { get; set; }
        public Nullable<int> IdSposobuPlatnosci { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Kontrahent Kontrahent { get; set; }
        public virtual SposobPlatnosci SposobPlatnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KosztUtrzymania> KosztUtrzymania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaNapraw> HistoriaNapraw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaFaktury> PozycjaFaktury { get; set; }
    }
}
