//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaNapraw
    {
        public int IdNaprawy { get; set; }
        public string RodzajNaprawy { get; set; }
        public string OpisNaprawy { get; set; }
        public System.DateTime DataRozpoczecia { get; set; }
        public Nullable<System.DateTime> DataZakonczenia { get; set; }
        public decimal KosztNaprawy { get; set; }
        public Nullable<decimal> CzasTrwaniaNaprawy { get; set; }
        public Nullable<int> GwarancjaMiesiecy { get; set; }
        public string StanKaretkiPrzedNaprawa { get; set; }
        public string StanKaretkiPoNaprawie { get; set; }
        public bool CzyZatwierdzona { get; set; }
        public int IdKaretki { get; set; }
        public Nullable<int> IdFaktury { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Faktura Faktura { get; set; }
        public virtual Karetka Karetka { get; set; }
        public virtual Kontrahent Kontrahent { get; set; }
    }
}
