//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrahent()
        {
            this.Faktura = new HashSet<Faktura>();
            this.HistoriaNapraw = new HashSet<HistoriaNapraw>();
            this.KosztUtrzymania = new HashSet<KosztUtrzymania>();
        }
    
        public int IdKontrahenta { get; set; }
        public string Nazwa { get; set; }
        public string Typ { get; set; }
        public string OsobaKontaktowa { get; set; }
        public string TelefonKontaktowy { get; set; }
        public string AdresEmail { get; set; }
        public string AdresSiedziby { get; set; }
        public string Miasto { get; set; }
        public string KodPocztowy { get; set; }
        public string NIP { get; set; }
        public string NumerKontaBankowego { get; set; }
        public string KategoriaBiznesowa { get; set; }
        public Nullable<System.DateTime> DataRozpoczeciaWspolpracy { get; set; }
        public Nullable<System.DateTime> DataZakonczeniaUmowy { get; set; }
        public string WarunkiPlatnosci { get; set; }
        public bool CzyPreferowany { get; set; }
        public Nullable<decimal> LacznaWartoscTransakcji { get; set; }
        public string StatusWspolpracy { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Faktura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaNapraw> HistoriaNapraw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KosztUtrzymania> KosztUtrzymania { get; set; }
    }
}
