//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KosztUtrzymania
    {
        public int IdKosztu { get; set; }
        public string RodzajKosztu { get; set; }
        public decimal Kwota { get; set; }
        public System.DateTime DataKosztu { get; set; }
        public string OpisSzczegolowy { get; set; }
        public Nullable<System.DateTime> DataKsiegowania { get; set; }
        public bool CzyZaksiegowany { get; set; }
        public string OkresRozliczeniowy { get; set; }
        public string NumerDowoduZakupu { get; set; }
        public string CentrumKosztowe { get; set; }
        public Nullable<bool> CzyJestCyklczny { get; set; }
        public Nullable<decimal> KwotaBudzetowa { get; set; }
        public string UwagiKsięgowe { get; set; }
        public int IdKaretki { get; set; }
        public Nullable<int> IdFaktury { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public Nullable<int> IdSposobuPlatnosci { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Faktura Faktura { get; set; }
        public virtual Karetka Karetka { get; set; }
        public virtual Kontrahent Kontrahent { get; set; }
        public virtual SposobPlatnosci SposobPlatnosci { get; set; }
    }
}
