//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalEntities : DbContext
    {
        public MedicalEntities()
            : base("name=MedicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CzlonekZespolu> CzlonekZespolu { get; set; }
        public virtual DbSet<Faktura> Faktura { get; set; }
        public virtual DbSet<HistoriaNapraw> HistoriaNapraw { get; set; }
        public virtual DbSet<Karetka> Karetka { get; set; }
        public virtual DbSet<Kontrahent> Kontrahent { get; set; }
        public virtual DbSet<KosztUtrzymania> KosztUtrzymania { get; set; }
        public virtual DbSet<OcenaZespolu> OcenaZespolu { get; set; }
        public virtual DbSet<Pacjent> Pacjent { get; set; }
        public virtual DbSet<Placowka> Placowka { get; set; }
        public virtual DbSet<PozycjaFaktury> PozycjaFaktury { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<RolaPracownika> RolaPracownika { get; set; }
        public virtual DbSet<SposobPlatnosci> SposobPlatnosci { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UdzielonaPomoc> UdzielonaPomoc { get; set; }
        public virtual DbSet<ZespolRatunkowy> ZespolRatunkowy { get; set; }
        public virtual DbSet<ZlecenieWyjazdu> ZlecenieWyjazdu { get; set; }
    }
}
