//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcenaZespolu
    {
        public int IdOceny { get; set; }
        public int Ocena { get; set; }
        public System.DateTime DataOceny { get; set; }
        public string Komentarz { get; set; }
        public string KryteriumOceny { get; set; }
        public Nullable<int> WagaOceny { get; set; }
        public Nullable<int> OcenaCzasuReakcji { get; set; }
        public Nullable<int> OcenaProfesjonalizmu { get; set; }
        public Nullable<int> OcenaSkutecznosci { get; set; }
        public Nullable<bool> CzyOtrzymanoFeedbackOdPacjenta { get; set; }
        public string SugerowaneUlepszenia { get; set; }
        public Nullable<int> OcenaStosowaniaStandardow { get; set; }
        public int IdZespolu { get; set; }
        public int IdOceniajacego { get; set; }
        public int IdWyjazdu { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual ZlecenieWyjazdu ZlecenieWyjazdu { get; set; }
        public virtual ZespolRatunkowy ZespolRatunkowy { get; set; }
    }
}
