//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacjent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacjent()
        {
            this.UdzielonaPomoc = new HashSet<UdzielonaPomoc>();
        }
    
        public int IdPacjenta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public System.DateTime DataUrodzenia { get; set; }
        public string AdresZamieszkania { get; set; }
        public string Miasto { get; set; }
        public string KodPocztowy { get; set; }
        public string TelefonKontaktowy { get; set; }
        public string AdresEmail { get; set; }
        public string Pesel { get; set; }
        public string Plec { get; set; }
        public string NumerKartyPacjenta { get; set; }
        public string GrupaKrwi { get; set; }
        public string InformacjeAlergie { get; set; }
        public string UbezpieczenieZdrowotne { get; set; }
        public string UwagiDodatkowe { get; set; }
        public string KontaktAwaryjnyImieNazwisko { get; set; }
        public string KontaktAwaryjnyTelefon { get; set; }
        public string ChorobyPrzewlekle { get; set; }
        public string RodzajNiepełnosprawności { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UdzielonaPomoc> UdzielonaPomoc { get; set; }
    }
}
