//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placowka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Placowka()
        {
            this.Karetka = new HashSet<Karetka>();
            this.Pracownik = new HashSet<Pracownik>();
            this.ZespolRatunkowy = new HashSet<ZespolRatunkowy>();
        }
    
        public int IdPlacowki { get; set; }
        public string NazwaPlacowki { get; set; }
        public string Adres { get; set; }
        public string Miasto { get; set; }
        public string KodPocztowy { get; set; }
        public string Telefon { get; set; }
        public string AdresEmail { get; set; }
        public string TypPlacowki { get; set; }
        public string GodzinyPracy { get; set; }
        public Nullable<int> LiczbaKaretek { get; set; }
        public Nullable<int> LiczbaZespolow { get; set; }
        public Nullable<int> PojemnoscGarazu { get; set; }
        public Nullable<System.DateTime> DataOtwarcia { get; set; }
        public Nullable<System.DateTime> DataOstatniejInspekcji { get; set; }
        public string Region { get; set; }
        public Nullable<decimal> Budzet { get; set; }
        public string ObszarZasieguRatunkowego { get; set; }
        public bool CzyMaAkredytacje { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karetka> Karetka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZespolRatunkowy> ZespolRatunkowy { get; set; }
    }
}
