//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjaFaktury
    {
        public int IdPozycji { get; set; }
        public int IdFaktury { get; set; }
        public string NazwaUslugi { get; set; }
        public decimal Ilosc { get; set; }
        public decimal CenaJednostkowaNetto { get; set; }
        public decimal StawkaVAT { get; set; }
        public decimal KwotaNetto { get; set; }
        public decimal KwotaVAT { get; set; }
        public decimal KwotaBrutto { get; set; }
        public string JednostkaMiary { get; set; }
        public string Kod { get; set; }
        public string KategoriaPozycji { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Faktura Faktura { get; set; }
    }
}
