//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownik()
        {
            this.CzlonekZespolu = new HashSet<CzlonekZespolu>();
            this.OcenaZespolu = new HashSet<OcenaZespolu>();
            this.UdzielonaPomoc = new HashSet<UdzielonaPomoc>();
            this.ZlecenieWyjazdu = new HashSet<ZlecenieWyjazdu>();
        }
    
        public int IdPracownika { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Pesel { get; set; }
        public Nullable<System.DateTime> DataUrodzenia { get; set; }
        public string AdresZamieszkania { get; set; }
        public string Miasto { get; set; }
        public string KodPocztowy { get; set; }
        public string TelefonSluzbowy { get; set; }
        public string AdresEmailSluzbowy { get; set; }
        public string NumerKontaBankowego { get; set; }
        public System.DateTime DataZatrudnienia { get; set; }
        public string StatusZatrudnienia { get; set; }
        public string NumerPrawaWykonywaniaZawodu { get; set; }
        public string KwalifikacjeDodatkowe { get; set; }
        public Nullable<System.DateTime> DataWaznosciBadanLekarskich { get; set; }
        public Nullable<decimal> StawkaGodzinowa { get; set; }
        public string TypUmowy { get; set; }
        public Nullable<int> LiczbaDniUrlopu { get; set; }
        public string PreferowanaZmiana { get; set; }
        public Nullable<System.DateTime> DataOstatniegoSzkolenia { get; set; }
        public int IdRoli { get; set; }
        public int IdPlacowki { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CzlonekZespolu> CzlonekZespolu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenaZespolu> OcenaZespolu { get; set; }
        public virtual Placowka Placowka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UdzielonaPomoc> UdzielonaPomoc { get; set; }
        public virtual RolaPracownika RolaPracownika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZlecenieWyjazdu> ZlecenieWyjazdu { get; set; }
    }
}
