//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolaPracownika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolaPracownika()
        {
            this.Pracownik = new HashSet<Pracownik>();
        }
    
        public int IdRoli { get; set; }
        public string NazwaRoli { get; set; }
        public int PoziomUprawnien { get; set; }
        public string OpisObowiazkow { get; set; }
        public string MinimalneWyksztalcenie { get; set; }
        public string WymaganeSzkolenia { get; set; }
        public bool CzyWymagaLicencji { get; set; }
        public Nullable<int> MaksymalnaLiczbaGodzinTygodniowo { get; set; }
        public Nullable<decimal> SredniaPlaca { get; set; }
        public string Benefity { get; set; }
        public Nullable<System.DateTime> DataOstatniejAktualizacji { get; set; }
        public string NazwaDzialu { get; set; }
        public bool CzyJestLideremZespolu { get; set; }
        public Nullable<int> LimitZatrudnienia { get; set; }
        public string WymaganeUmiejetnosci { get; set; }
        public string RolaNastepnegoEtapuKariery { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracownik { get; set; }
    }
}
