//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SposobPlatnosci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SposobPlatnosci()
        {
            this.Faktura = new HashSet<Faktura>();
            this.KosztUtrzymania = new HashSet<KosztUtrzymania>();
        }
    
        public int IdSposobuPlatnosci { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public bool CzyWymagaPotwierdzenia { get; set; }
        public string RodzajTransakcji { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Faktura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KosztUtrzymania> KosztUtrzymania { get; set; }
    }
}
