//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UdzielonaPomoc
    {
        public int IdPomocy { get; set; }
        public System.DateTime DataPomocy { get; set; }
        public Nullable<System.TimeSpan> CzasRozpoczecia { get; set; }
        public Nullable<System.TimeSpan> CzasZakonczenia { get; set; }
        public string OpisPomocy { get; set; }
        public string ProceduryMedyczne { get; set; }
        public string WynikInterwencji { get; set; }
        public int CzasTrwaniaMinuty { get; set; }
        public string LokalizacjaInterwencji { get; set; }
        public string WymaganySprzet { get; set; }
        public Nullable<bool> CzyWymagalTransportu { get; set; }
        public string PriorytetInterwencji { get; set; }
        public string KodDiagnozyICD10 { get; set; }
        public string SzpitalTransportu { get; set; }
        public string StanPacjentaPrzyPrzekazaniu { get; set; }
        public Nullable<bool> CzyBylWymaganyUdziałPolicji { get; set; }
        public int IdPacjenta { get; set; }
        public int IdZespolu { get; set; }
        public Nullable<int> IdKaretki { get; set; }
        public int IdWyjazdu { get; set; }
        public int IdAutoraRaportu { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Karetka Karetka { get; set; }
        public virtual Pacjent Pacjent { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual ZlecenieWyjazdu ZlecenieWyjazdu { get; set; }
        public virtual ZespolRatunkowy ZespolRatunkowy { get; set; }
    }
}
