//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZespolRatunkowy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZespolRatunkowy()
        {
            this.OcenaZespolu = new HashSet<OcenaZespolu>();
            this.UdzielonaPomoc = new HashSet<UdzielonaPomoc>();
            this.ZlecenieWyjazdu = new HashSet<ZlecenieWyjazdu>();
            this.ZespolPracownik = new HashSet<ZespolPracownik>();
        }
    
        public int IdZespolu { get; set; }
        public string NazwaZespolu { get; set; }
        public int LiczbaCzlonkow { get; set; }
        public string Specjalizacja { get; set; }
        public System.DateTime DataUtworzenia { get; set; }
        public string StatusZespolu { get; set; }
        public string TelefonKontaktowy { get; set; }
        public string Zmiana { get; set; }
        public Nullable<System.DateTime> DataOstatniegoSzkolenia { get; set; }
        public Nullable<decimal> SredniaOcena { get; set; }
        public Nullable<System.DateTime> DataOstatniegoWyjazdu { get; set; }
        public Nullable<int> LiczbaWszystkichWyjazdow { get; set; }
        public string Certyfikaty { get; set; }
        public Nullable<int> IdKaretki { get; set; }
        public int IdPlacowki { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Karetka Karetka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenaZespolu> OcenaZespolu { get; set; }
        public virtual Placowka Placowka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UdzielonaPomoc> UdzielonaPomoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZlecenieWyjazdu> ZlecenieWyjazdu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZespolPracownik> ZespolPracownik { get; set; }
    }
}
