//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZlecenieWyjazdu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZlecenieWyjazdu()
        {
            this.OcenaZespolu = new HashSet<OcenaZespolu>();
            this.UdzielonaPomoc = new HashSet<UdzielonaPomoc>();
        }
    
        public int IdWyjazdu { get; set; }
        public System.DateTime DataCzasZgloszenia { get; set; }
        public string AdresZdarzenia { get; set; }
        public string TypZdarzenia { get; set; }
        public string Priorytet { get; set; }
        public string StatusZlecenia { get; set; }
        public string OpisZdarzenia { get; set; }
        public Nullable<System.DateTime> CzasWyjazdu { get; set; }
        public Nullable<System.DateTime> CzasPrzyjazduNaMiejsce { get; set; }
        public Nullable<System.DateTime> CzasPowrotuDoBazy { get; set; }
        public string TelefonDzwoniacego { get; set; }
        public Nullable<int> CzasReakcjiSekundy { get; set; }
        public Nullable<decimal> DystansKm { get; set; }
        public Nullable<int> LiczbaPacjentow { get; set; }
        public string WarunkiPogodowe { get; set; }
        public string WymaganeDodatkoweWsparcie { get; set; }
        public int IdDyspozytora { get; set; }
        public int IdZespolu { get; set; }
        public Nullable<int> IdKaretki { get; set; }
        public bool CzyAktywny { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string KtoWykasowal { get; set; }
        public int WersjaDanych { get; set; }
    
        public virtual Karetka Karetka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenaZespolu> OcenaZespolu { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UdzielonaPomoc> UdzielonaPomoc { get; set; }
        public virtual ZespolRatunkowy ZespolRatunkowy { get; set; }
    }
}
